version: '3.8'
services:
   web:
       build: .
       command: python manage.py runserver 0.0.0.0:8000
       volumes:
            - .:/app
       ports:
           - 1337:8000
       depends_on:
           - redis

   redis:
       image: redis

   celery:
       build: .
       command: celery -A Stepik worker -l info
       volumes:
           - .:/app
       depends_on:
           - redis

   celery-beat:
       build: .
       command: celery -A Stepik beat -l info
       volumes:
           - .:/app
       depends_on:
           - redis

   flower:
       build: .
       command: flower -A Stepik --port=5555
       volumes:
           - .:/app
       ports:
           - 5555:5555
       depends_on:
           - redis
