# Generated by Django 5.0.2 on 2024-02-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_cover',
            field=models.ImageField(blank=True, null=True, upload_to='product_covers/%Y', verbose_name='Обложка'),
        ),
    ]
