# Generated by Django 5.0.2 on 2024-02-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_product_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_cover',
            field=models.ImageField(default='default', upload_to='product_covers/%Y', verbose_name='Обложка'),
            preserve_default=False,
        ),
    ]
