# Generated by Django 5.0.2 on 2024-02-28 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_student_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Максимальное количество студентов в группе'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='products.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='s', max_length=120, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
