# Generated by Django 5.0.2 on 2024-02-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_max_student_quantity_alter_lesson_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='max_student_quantity',
            field=models.PositiveIntegerField(default=5, verbose_name='Максимальное количество студентов в группе'),
        ),
    ]
