# Generated by Django 5.0.2 on 2024-02-29 11:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_is_published_alter_group_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='author',
        ),
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.ManyToManyField(related_name='product_author', to=settings.AUTH_USER_MODEL, verbose_name='Авторы'),
        ),
    ]
